package pojo;

// Generated Nov 22, 2016 5:58:15 PM by Hibernate Tools 3.4.0.CR1

/**
 * Attendancemaster generated by hbm2java
 */
public class Attendancemaster implements java.io.Serializable {

	private Integer id;
	private String fname;
	private String mname;
	private String lname;
	private String email;
	private Integer day;
	private Integer month;
	private Integer year;
	private String status;

	public Attendancemaster() {
	}

	public Attendancemaster(String fname, String mname, String lname, String email, Integer day, Integer month,
			Integer year, String status) {
		this.fname = fname;
		this.mname = mname;
		this.lname = lname;
		this.email = email;
		this.day = day;
		this.month = month;
		this.year = year;
		this.status = status;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getFname() {
		return this.fname;
	}

	public void setFname(String fname) {
		this.fname = fname;
	}

	public String getMname() {
		return this.mname;
	}

	public void setMname(String mname) {
		this.mname = mname;
	}

	public String getLname() {
		return this.lname;
	}

	public void setLname(String lname) {
		this.lname = lname;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public Integer getDay() {
		return this.day;
	}

	public void setDay(Integer day) {
		this.day = day;
	}

	public Integer getMonth() {
		return this.month;
	}

	public void setMonth(Integer month) {
		this.month = month;
	}

	public Integer getYear() {
		return this.year;
	}

	public void setYear(Integer year) {
		this.year = year;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

}
