package pojo;

// Generated Nov 22, 2016 5:58:15 PM by Hibernate Tools 3.4.0.CR1

/**
 * Blog generated by hbm2java
 */
public class Blog implements java.io.Serializable {

	private Integer id;
	private String news;
	private String description;
	private Integer day;
	private Integer month;
	private Integer year;

	public Blog() {
	}

	public Blog(String news, String description, Integer day, Integer month, Integer year) {
		this.news = news;
		this.description = description;
		this.day = day;
		this.month = month;
		this.year = year;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getNews() {
		return this.news;
	}

	public void setNews(String news) {
		this.news = news;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Integer getDay() {
		return this.day;
	}

	public void setDay(Integer day) {
		this.day = day;
	}

	public Integer getMonth() {
		return this.month;
	}

	public void setMonth(Integer month) {
		this.month = month;
	}

	public Integer getYear() {
		return this.year;
	}

	public void setYear(Integer year) {
		this.year = year;
	}

}
