package pojo;

// Generated Nov 22, 2016 5:58:15 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * Leavemaster generated by hbm2java
 */
public class Leavemaster implements java.io.Serializable {

	private Integer id;
	private Registration registration;
	private String leavetype;
	private String description;
	private Date startdate;
	private Date enddate;
	private String department;
	private String status;
	private Date applydate;

	public Leavemaster() {
	}

	public Leavemaster(Registration registration, String leavetype, String description, Date startdate, Date enddate,
			String department, String status, Date applydate) {
		this.registration = registration;
		this.leavetype = leavetype;
		this.description = description;
		this.startdate = startdate;
		this.enddate = enddate;
		this.department = department;
		this.status = status;
		this.applydate = applydate;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Registration getRegistration() {
		return this.registration;
	}

	public void setRegistration(Registration registration) {
		this.registration = registration;
	}

	public String getLeavetype() {
		return this.leavetype;
	}

	public void setLeavetype(String leavetype) {
		this.leavetype = leavetype;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Date getStartdate() {
		return this.startdate;
	}

	public void setStartdate(Date startdate) {
		this.startdate = startdate;
	}

	public Date getEnddate() {
		return this.enddate;
	}

	public void setEnddate(Date enddate) {
		this.enddate = enddate;
	}

	public String getDepartment() {
		return this.department;
	}

	public void setDepartment(String department) {
		this.department = department;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public Date getApplydate() {
		return this.applydate;
	}

	public void setApplydate(Date applydate) {
		this.applydate = applydate;
	}

}
