package pojo;

// Generated Nov 22, 2016 5:58:15 PM by Hibernate Tools 3.4.0.CR1

/**
 * Online generated by hbm2java
 */
public class Online implements java.io.Serializable {

	private Integer onid;
	private Boolean olFlag;
	private Integer olUmId;

	public Online() {
	}

	public Online(Boolean olFlag, Integer olUmId) {
		this.olFlag = olFlag;
		this.olUmId = olUmId;
	}

	public Integer getOnid() {
		return this.onid;
	}

	public void setOnid(Integer onid) {
		this.onid = onid;
	}

	public Boolean getOlFlag() {
		return this.olFlag;
	}

	public void setOlFlag(Boolean olFlag) {
		this.olFlag = olFlag;
	}

	public Integer getOlUmId() {
		return this.olUmId;
	}

	public void setOlUmId(Integer olUmId) {
		this.olUmId = olUmId;
	}

}
