package pojo;

// Generated Nov 22, 2016 5:58:15 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Registration generated by hbm2java
 */
public class Registration implements java.io.Serializable {

	private Integer regId;
	private Role role;
	private String fname;
	private String mname;
	private String lname;
	private String email;
	private String password;
	private Date dob;
	private String gender;
	private String contactno;
	private String address;
	private Integer rgFirstattemptflag;
	private Set studprojects = new HashSet(0);
	private Set leavemasters = new HashSet(0);

	public Registration() {
	}

	public Registration(Role role, String fname, String mname, String lname, String email, String password, Date dob,
			String gender, String contactno, String address) {
		this.role = role;
		this.fname = fname;
		this.mname = mname;
		this.lname = lname;
		this.email = email;
		this.password = password;
		this.dob = dob;
		this.gender = gender;
		this.contactno = contactno;
		this.address = address;
	}

	public Registration(Role role, String fname, String mname, String lname, String email, String password, Date dob,
			String gender, String contactno, String address, Integer rgFirstattemptflag, Set studprojects,
			Set leavemasters) {
		this.role = role;
		this.fname = fname;
		this.mname = mname;
		this.lname = lname;
		this.email = email;
		this.password = password;
		this.dob = dob;
		this.gender = gender;
		this.contactno = contactno;
		this.address = address;
		this.rgFirstattemptflag = rgFirstattemptflag;
		this.studprojects = studprojects;
		this.leavemasters = leavemasters;
	}

	public Integer getRegId() {
		return this.regId;
	}

	public void setRegId(Integer regId) {
		this.regId = regId;
	}

	public Role getRole() {
		return this.role;
	}

	public void setRole(Role role) {
		this.role = role;
	}

	public String getFname() {
		return this.fname;
	}

	public void setFname(String fname) {
		this.fname = fname;
	}

	public String getMname() {
		return this.mname;
	}

	public void setMname(String mname) {
		this.mname = mname;
	}

	public String getLname() {
		return this.lname;
	}

	public void setLname(String lname) {
		this.lname = lname;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public Date getDob() {
		return this.dob;
	}

	public void setDob(Date dob) {
		this.dob = dob;
	}

	public String getGender() {
		return this.gender;
	}

	public void setGender(String gender) {
		this.gender = gender;
	}

	public String getContactno() {
		return this.contactno;
	}

	public void setContactno(String contactno) {
		this.contactno = contactno;
	}

	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public Integer getRgFirstattemptflag() {
		return this.rgFirstattemptflag;
	}

	public void setRgFirstattemptflag(Integer rgFirstattemptflag) {
		this.rgFirstattemptflag = rgFirstattemptflag;
	}

	public Set getStudprojects() {
		return this.studprojects;
	}

	public void setStudprojects(Set studprojects) {
		this.studprojects = studprojects;
	}

	public Set getLeavemasters() {
		return this.leavemasters;
	}

	public void setLeavemasters(Set leavemasters) {
		this.leavemasters = leavemasters;
	}

}
