package pojo;

// Generated Nov 22, 2016 5:58:15 PM by Hibernate Tools 3.4.0.CR1

/**
 * Studproject generated by hbm2java
 */
public class Studproject implements java.io.Serializable {

	private Integer proid;
	private Registration registration;
	private String protitle;
	private String description;
	private String language;

	public Studproject() {
	}

	public Studproject(Registration registration, String protitle, String description, String language) {
		this.registration = registration;
		this.protitle = protitle;
		this.description = description;
		this.language = language;
	}

	public Integer getProid() {
		return this.proid;
	}

	public void setProid(Integer proid) {
		this.proid = proid;
	}

	public Registration getRegistration() {
		return this.registration;
	}

	public void setRegistration(Registration registration) {
		this.registration = registration;
	}

	public String getProtitle() {
		return this.protitle;
	}

	public void setProtitle(String protitle) {
		this.protitle = protitle;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public String getLanguage() {
		return this.language;
	}

	public void setLanguage(String language) {
		this.language = language;
	}

}
